### ISSUE TITLE
autodect Map<String, String> from `additionalProperties`

### ISSUE THREAD

**Issue by hauner** [openapi-processor/openapi-processor-base#10]
extracted from on openapi-processor/openapi-processor-spring/issues/150

automatically detect a `Map<String, String>`  from `additionalProperties` without an explicit mapping:

```yaml
# ...
type: object
additionalProperties:
  type: string
```
