### ISSUE TITLE
autodect Map<String, ComplexType> from `additionalProperties`

### ISSUE THREAD

**Issue by hauner** [openapi-processor/openapi-processor-base#11]
extracted from on openapi-processor/openapi-processor-spring/issues/150

if #10 works and produces maintainable code try to automatically detect a `Map<String, ComplexType>`  from `additionalProperties` without an explicit mapping:

```yaml
# ...
type: object
additionalProperties:
  type: array
  items:
    type: string
```

or even more complex:

`additionalProperties` may contain an object that should be generated:

```yaml
# ...
type: object
additionalProperties:
  type: object
  properties:
    foo:
      type: string
    bar:
      type: array
      items:
        type: string
```
