### ISSUE TITLE
using a null mapping looses the constraints

### ISSUE THREAD

**Issue by hauner** [openapi-processor/openapi-processor-base#143]
using a null mapping:

```yaml
openapi-processor-mapping: v7

options:
  bean-validation: true

map:
  paths:
    /foo:
      null: org.openapitools.jackson.nullable.JsonNullable
```

on a property 

```yaml
      properties:
        bar:
          nullable: true
          type: string
          maxLength: 4
```

doesn't add the constraint to the generated property.
