### ISSUE TITLE
Add enum names via x-enumNames parameter

### ISSUE THREAD

**Issue by kirillsulim** [openapi-processor/openapi-processor-base#144]
In some of my projects I have to describe an openAPI interface with enum with values like "01", "02", etc. Those are codes for specific business cases. I would like to operate in my code with enum values like `ClientType.BASIC` instead of `ClientType._01` or use string values for such cases. As I found out there are some openAPI generators that uses extensions like `x-enumNames` for such cases (see [this stackowerflow thread for more info](https://stackoverflow.com/questions/66465888/how-to-define-enum-mapping-in-openapi)).

So I propose following logic:
For enum schema like:
```yaml
NamedEnum:
  type: string
  enum:
    - "1"
    - "2"
    - "3"
  x-enumNames:
    - "ONE"
    - "TWO"
    - "THREE"
```
generate following java code:
```java
public enum NamedEnum {
    ONE("1"),
    TWO("2"),
    THREE("3");

    // ... some code ommited...
}
```
