### ISSUE TITLE
bad enum creation

### ISSUE THREAD

**Issue by hauner** [openapi-processor/openapi-processor-base#145]
```yaml
components:
  schemas:
    AnEnum:
      type: string
      enum:
        - "1"
        - "2"
 ```

creates

```java
public enum Enum {
    INVALID("1"),
    INVALID("2");
    ...
}
