### ISSUE TITLE
type annotation mapping ignored with model-name-suffix

### ISSUE THREAD

**Issue by hauner** [openapi-processor/openapi-processor-base#158]
using a mapping like this:

```yaml
openapi-processor-mapping: v8
options:
  model-name-suffix: Resource

maps:
  types:
    - type: Foo @ io.openapiprocessor.Annotation()
```

does not add the annotation.

After disabling `model-name-suffix` the annotation gets added.
