### ISSUE TITLE
use x-tension value in annotation mapping

### ISSUE THREAD

**Issue by hauner** [openapi-processor/openapi-processor-base#190]
Having an x-tension property with value

```yaml
    Foo:
      type: object
      properties:
        bar:
          type: integer
          x-foobar: raboof
```

it would probably be nice if I could pass the value to the annotation. 

how wold the mapping look like?

```yaml
  extensions:
    # the mapping expects the source type to be a `string`. It would need 
    # - an identifier to represent the x-tension value and
    # - an identifier as placeholder for the annotation parameter

    # placeholder could look like this
    x-foobar: ?? @ io.openapiprocessor.annotation.Foobar(value = {value})
 
    # value source type could be this?
    x-foobar: {value} @ io.openapiprocessor.annotation.Foobar(value = {value})
```
