### ISSUE TITLE
doesn't find nested schemas of `additionalProperties`

### ISSUE THREAD

**Issue by hauner** [openapi-processor/openapi-processor-base#24]
assuming `Values` is nested schema of `additionalProperties`.

this prevents mappings like

```yaml
map:
  types:
    - type: Values => java.util.Map<java.lang.String, {package-name}.model.Value>>
    - type: MultiValues => java.util.Map<java.lang.String, java.util.List<{package-name}.model.Value>>>
```
