### ISSUE TITLE
Add annotation to every model Class

### ISSUE THREAD

**Issue by joellp** [openapi-processor/openapi-processor-base#30]
I would like to add Lombok annotations to every model class. The following mapping config works:
```yaml
map:
  types:
    - type: MyType @ lombok.Builder
 ```
However, this is quite troublesome to add for every type. I cannot find a way to do this for every model class. I tried to the following, but unfortunately it does not work:

```yaml
map:
  types:
    - type: object @ lombok.Builder
```

Is there a way to add an annotation for every model class?
