### ISSUE TITLE
Add an annotation only to the model class

### ISSUE THREAD

**Issue by joellp** [openapi-processor/openapi-processor-base#33]
I have the following mapping:

```yaml
openapi-processor-mapping: v2

map:
  types:    
    - type: Type1 @ lombok.Builder
    - type: Type2 @ lombok.Builder
```

This generates a model class:
```java
@Builder
@Generated(value = "openapi-processor-micronaut", version = "2023.2.2", date = "2023-06-27T16:41:57.323668900+02:00")
public class Type1 {

    // content omitted

}
```

and model class that uses another model class
```java
@Builder
@Generated(value = "openapi-processor-micronaut", version = "2023.2.2", date = "2023-06-27T16:41:57.323668900+02:00")
public class Type2 {
   
    @Builder // This does not compile
    @JsonProperty("location")
    private Type1 location;    

    public Type1 getLocation() {
        return location;
    }

    public void setLocation(Type1 location) {
        this.location = location;
    }
}
```

Is there a way to add the annotation just for the class and not to the variables?
