### ISSUE TITLE
mapping with generic types may not generate nested classes

### ISSUE THREAD

**Issue by hauner** [openapi-processor/openapi-processor-base#91]
having a mapping like this

```yaml
map:
  types:
    - type: Values => java.util.Map<java.lang.String, {package-name}.model.Value>>
```

the processor does generate the `Value` class but does NOT generate the class of a nested object.
